# Generated by Django 5.0.6 on 2025-08-24 15:46

import api.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='المعرف')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('location', models.CharField(default='Aïn El Kebira', max_length=255, verbose_name='المكان')),
                ('participants', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد المشاركين')),
                ('duration', models.CharField(blank=True, max_length=50, null=True, verbose_name='المدة')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='الفئة')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('ongoing', 'جاري'), ('completed', 'مكتمل')], max_length=100, verbose_name='الحالة')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('color', models.CharField(blank=True, choices=[('from-yellow-400 to-orange-500', 'أصفر → برتقالي'), ('from-cyan-400 to-blue-500', 'سماوي → أزرق'), ('from-indigo-400 to-purple-500', 'نيلي → بنفسجي'), ('from-purple-400 to-pink-500', 'بنفسجي → وردي'), ('from-green-400 to-blue-500', 'أخضر → أزرق'), ('from-orange-400 to-red-500', 'برتقالي → أحمر')], max_length=50, null=True, verbose_name='اللون')),
            ],
            options={
                'verbose_name': 'نشاط',
                'verbose_name_plural': 'الأنشطة',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('applicationId', models.AutoField(default=0, primary_key=True, serialize=False, verbose_name='المعرف')),
                ('photo', models.ImageField(upload_to=api.models.Application_photo_path, verbose_name='الصورة الشخصية')),
                ('id_card', models.ImageField(upload_to=api.models.Application_id_card_path, verbose_name='صورة بطاقة الهوية')),
                ('fullName', models.CharField(max_length=255, verbose_name='الاسم الكامل')),
                ('email', models.EmailField(max_length=255, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=50, verbose_name='رقم الهاتف')),
                ('age', models.PositiveIntegerField(verbose_name='العمر')),
                ('interests', models.TextField(verbose_name='الاهتمامات')),
                ('experience', models.TextField(blank=True, null=True, verbose_name='الخبرات السابقة')),
                ('motivation', models.TextField(verbose_name='الدافع للانضمام')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقديم')),
            ],
            options={
                'verbose_name': 'طلب الانضمام',
                'verbose_name_plural': 'طلبات الانضمام',
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='الاسم الكامل')),
                ('role', models.CharField(choices=[('president', 'رئيس'), ('vice1', 'نائب أول'), ('vice2', 'نائب ثاني'), ('general_secretary', 'الكاتب العام'), ('vice_secretary', 'نائب الكاتب العام'), ('treasurer', 'أمين المال'), ('vice_treasurer', 'نائب أمين المال'), ('member1', 'عضو أول'), ('member2', 'عضو ثاني'), ('social_committee', 'رئيس لجنة الشؤون الاجتماعية'), ('culture_committee', 'رئيس لجنة النشاطات الثقافية'), ('sports_committee', 'رئيس لجنة النشاطات الرياضية')], max_length=100, verbose_name='الدور')),
                ('image', models.ImageField(blank=True, null=True, upload_to='members_images/', verbose_name='الصورة')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='نبذة قصيرة')),
                ('joinDate', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاريخ الانضمام')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='الهاتف')),
                ('education', models.CharField(blank=True, max_length=255, null=True, verbose_name='المستوى التعليمي')),
                ('type', models.CharField(choices=[('admin', 'عضو إداري'), ('normal', 'عضو عادي')], default='normal', max_length=100, verbose_name='نوع العضو')),
                ('color', models.CharField(blank=True, choices=[('bg-primary', 'أزرق رئيسي'), ('bg-secondary', 'رمادي ثانوي'), ('bg-accent', 'أخضر بارز'), ('bg-chart-3', 'برتقالي'), ('bg-chart-4', 'بنفسجي'), ('bg-chart-5', 'أحمر')], max_length=50, null=True, verbose_name='اللون')),
                ('icon', models.CharField(blank=True, choices=[('Crown', '👑 تاج (رئيس / قيادي)'), ('Star', '⭐ نجم (تميز)'), ('Award', '🏅 جائزة (إنجاز)'), ('Users', '👥 أعضاء / فريق')], max_length=100, null=True, verbose_name='الأيقونة')),
            ],
            options={
                'verbose_name': 'عضو',
                'verbose_name_plural': 'الاعضاء',
            },
        ),
        migrations.CreateModel(
            name='ActivityAchievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الإنجاز')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='api.activity', verbose_name='النشاط')),
            ],
            options={
                'verbose_name': 'إنجاز النشاط',
                'verbose_name_plural': 'إنجازات النشاط',
            },
        ),
        migrations.CreateModel(
            name='ActivityHighlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='النقطة المميزة')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='api.activity', verbose_name='النشاط')),
            ],
            options={
                'verbose_name': 'ميزة النشاط',
                'verbose_name_plural': 'مميزات النشاط',
            },
        ),
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=api.models.activity_image_path, verbose_name='الصورة')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.activity', verbose_name='النشاط')),
            ],
            options={
                'verbose_name': 'صورة النشاط',
                'verbose_name_plural': 'صور النشاط',
            },
        ),
        migrations.CreateModel(
            name='ActivityVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=api.models.activity_video_path, verbose_name='الفيديو')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='api.activity', verbose_name='النشاط')),
            ],
            options={
                'verbose_name': 'فيديو النشاط',
                'verbose_name_plural': 'فيديوهات النشاط',
            },
        ),
        migrations.CreateModel(
            name='MemberAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='الإنجاز')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='api.members')),
            ],
        ),
        migrations.CreateModel(
            name='MemberSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='المهارة')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='api.members')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('excerpt', models.TextField(verbose_name='ملخص قصير')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('time', models.TimeField(verbose_name='الوقت')),
                ('category', models.CharField(max_length=100, verbose_name='التصنيف')),
                ('type', models.CharField(choices=[('announcement', 'إعلان'), ('achievement', 'إنجاز'), ('reminder', 'تذكير'), ('workshop', 'ورشة عمل'), ('initiative', 'مبادرة')], max_length=100, verbose_name='نوع الخبر')),
                ('icon', models.CharField(blank=True, choices=[('Megaphone', '📢 مكبر صوت (إعلان)'), ('Users', '👥 أشخاص (مستخدمين / مجتمع)'), ('Star', '⭐ نجمة (تميز / إنجاز)'), ('Bell', '🔔 جرس (تنبيه / تذكير)'), ('Trophy', '🏆 كأس (جائزة / نجاح)')], max_length=100, null=True, verbose_name='الأيقونة')),
                ('color', models.CharField(blank=True, choices=[('text-primary', 'أزرق أساسي'), ('text-secondary', 'رمادي ثانوي'), ('text-accent', 'أخضر بارز'), ('text-chart-3', 'برتقالي إحصائي'), ('text-chart-4', 'بنفسجي إحصائي')], max_length=50, null=True, verbose_name='اللون')),
                ('bgColor', models.CharField(blank=True, choices=[('bg-primary/10', 'خلفية زرقاء فاتحة'), ('bg-secondary/10', 'خلفية رمادية فاتحة'), ('bg-accent/10', 'خلفية خضراء فاتحة'), ('bg-chart-3/10', 'خلفية برتقالية فاتحة'), ('bg-chart-4/10', 'خلفية بنفسجية فاتحة')], max_length=50, null=True, verbose_name='لون الخلفية')),
                ('image', models.ImageField(upload_to=api.models.news_image_path, verbose_name='الصورة')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='عدد الإعجابات')),
                ('featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('author', models.ForeignKey(blank=True, limit_choices_to={'type': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.members', verbose_name='الكاتب')),
            ],
            options={
                'verbose_name': 'الخبر',
                'verbose_name_plural': 'الاخبار',
            },
        ),
    ]
