# Generated by Django 5.0.6 on 2025-08-24 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='color',
        ),
    ]
