# Generated by Django 5.0.6 on 2025-08-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_activity_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('معلق', 'معلق'), ('قادم', 'قادم'), ('مكتمل', 'مكتمل')], max_length=100, verbose_name='الحالة'),
        ),
    ]
