# Generated by Django 5.0.6 on 2025-08-24 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_activity_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='bgColor',
        ),
        migrations.RemoveField(
            model_name='news',
            name='color',
        ),
        migrations.RemoveField(
            model_name='news',
            name='icon',
        ),
    ]
