# Generated by Django 5.0.6 on 2025-08-24 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_news_bgcolor_remove_news_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
    ]
