# Generated by Django 5.0.6 on 2025-08-24 19:40

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='id_card',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.Application_id_card_path, verbose_name='صورة بطاقة الهوية'),
        ),
    ]
