# Generated by Django 5.0.6 on 2025-08-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_application_id_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicationId',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='المعرف'),
        ),
    ]
