# Generated by Django 5.0.6 on 2025-08-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_application_applicationid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='fullName',
            field=models.CharField(max_length=255, unique=True, verbose_name='الاسم الكامل'),
        ),
    ]
