# Generated by Django 5.0.6 on 2025-08-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_application_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='البريد الإلكتروني')),
                ('reason', models.CharField(choices=[('membership', 'استفسار عن العضوية'), ('activities', 'الأنشطة والفعاليات'), ('partnership', 'شراكة أو تعاون'), ('complaint', 'شكوى أو اقتراح'), ('other', 'أخرى')], max_length=20)),
                ('phone', models.CharField(max_length=10, verbose_name='رقم الهاتف')),
                ('subject', models.CharField(max_length=200, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
