# Generated by Django 5.0.6 on 2025-08-25 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='reason',
            new_name='contactReason',
        ),
    ]
