# Generated by Django 5.0.6 on 2025-08-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_reason_contact_contactreason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='color',
        ),
        migrations.RemoveField(
            model_name='members',
            name='icon',
        ),
        migrations.AlterField(
            model_name='members',
            name='role',
            field=models.CharField(choices=[('president', 'رئيس'), ('vice1', 'نائب أول'), ('vice2', 'نائب ثاني'), ('general_secretary', 'الكاتب العام'), ('vice_secretary', 'نائب الكاتب العام'), ('treasurer', 'أمين المال'), ('vice_treasurer', 'نائب أمين المال'), ('member1', 'عضو أول'), ('member2', 'عضو ثاني'), ('social_committee', 'رئيس لجنة الشؤون الاجتماعية'), ('culture_committee', 'رئيس لجنة النشاطات الثقافية'), ('sports_committee', 'رئيس لجنة النشاطات الرياضية'), ('normal', 'عادي')], max_length=100, verbose_name='الدور'),
        ),
    ]
