# Generated by Django 5.0.6 on 2025-08-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_members_color_remove_members_icon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='type',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('قادم', 'قادم'), ('مكتمل', 'مكتمل')], max_length=100, verbose_name='الحالة'),
        ),
    ]
