# Generated by Django 5.0.6 on 2025-09-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_type_news_category_alter_activity_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(blank=True, choices=[('مخيم', 'مخيم'), ('ورشة', 'ورشة'), ('رياضة', 'رياضة'), ('فنون', 'فنون'), ('استكشاف', 'استكشاف'), ('مؤتمر', 'مؤتمر')], max_length=100, null=True, verbose_name='الفئة'),
        ),
    ]
